# Generated by Django 4.2.4 on 2023-09-01 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0003_userprofile_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('messages', models.JSONField()),
                ('date_of_post', models.DateTimeField(auto_now_add=True)),
                ('pdfsize', models.PositiveIntegerField()),
                ('pdfname', models.CharField(max_length=255)),
            ],
        ),
    ]
